[package]
name = "bdk-core-wallet"
version = "0.1.0"
edition = "2021"

[dependencies]
bdk = {version = "0.29.0", default-features = false, features = ["all-keys", "key-value-db", "rpc"]}
dirs-next = "2.0.0"
